---
# Creates user from users/tech-breakfast.yml

- hosts: all

  vars_files:
    - users/tech-breakfast.yml # All users
    

  gather_facts: no
  become: true
   
  tasks:

  - name: Ensure group "techbreakfast" exists
    group:
     name: "techbreakfast"
     state: present
    
  - name: Add user
    user: 
     name: "{{ item }}"
     groups: "techbreakfast"
     state: present
    with_items: "{{ users }}"
    
  - name: Add user to the sudoers
    copy:
      dest: "/etc/sudoers.d/{{ item }}"
      content: "{{ item }}  ALL=(ALL)  NOPASSWD: ALL"
    with_items: "{{ users }}"

  - name: "Add authorized keys"
    authorized_key:
     user: "{{ item }}"
     key: "{{ lookup('file', 'users/'+ item + '.pub') }}"
    with_items: "{{ users }}"

